- name: Install nginx and PHP
  apt:
    name:
      - mariadb-client
      - nginx
      - php-cli
      - php-curl
      - php-fpm
      - php-gd
      - php-intl
      - php-mbstring
      - php-mysql
      - php-soap
      - php-xml
      - php-xmlrpc
      - php-zip
    state: present
    update_cache: yes
  notify: Restart web stack

- name: Configure nginx
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 0755
  notify: Restart nginx

- name: Configure nginx for WP site
  copy:
    src: files/wordpress_nginx.conf
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 0755
  notify: Restart nginx

- name: Delete default nginx config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart nginx


- name: Create web directory
  file:
    path: /usr/share/nginx/html/wordpress
    state: directory
    mode: 0755
    owner: www-data
    group: www-data

- name: Install wp-cli
  get_url:
    url='https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar'
    dest="/usr/local/bin/wp"
    force_basic_auth=yes
    mode=0755

- name: Download WP Core
  become: yes
  become_user: www-data
  register: wp_core_download
  command: /usr/local/bin/wp core download
  args:
    chdir: /usr/share/nginx/html/wordpress/
  failed_when: "wp_core_download.rc != 0 and 'already be present' not in wp_core_download.stderr"

- name: Create WP config file
  become: yes
  become_user: www-data
  register: wp_config_create
  command: /usr/local/bin/wp config create --dbname="{{ rds_db_name }}" --dbuser="{{ rds_username }}" --dbpass="{{ rds_password }}" --dbhost="{{ hostvars['localhost']['rds_wp_endpoint'] }}"
  args:
    chdir: /usr/share/nginx/html/wordpress/
  failed_when: "wp_config_create.rc != 0 and 'already exists' not in wp_config_create.stderr"

- name: Install WordPress
  become: yes
  become_user: www-data
  register: wp_install
  command: /usr/local/bin/wp core install --url="{{ hostvars['localhost']['varnish_elb_endpoint'] }}" --title="{{ wordpress_blog_title }}" --admin_user="{{ wordpress_admin_username }}" --admin_password="{{ wordpress_admin_password }}" --admin_email="{{ wordpress_admin_email }}"
  args:
    chdir: /usr/share/nginx/html/wordpress/
